name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17.0.9'
          distribution: 'adopt'

      - name: Compile Java code
          javac -d ./target ./src/mon_projet_test/*.java ./src/junit.monprojet.test/*.java

