name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17.0.9'
          distribution: 'adopt'

      - name: Compile Java code
        run: javac -d ./target/mon_projet_test

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Run JUnit tests
        run: |
          java -cp ./target:./lib/* org.junit.runner.JUnitCore junit.monprojet.test.PorteMonnaieTest junit.monprojet.test.SommeArgentTest
